[package]
name = "day04"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "default"
harness = false
