[package]
name = "day02"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
itoa = "^1.0"

[dev-dependencies]
rstest.workspace = true
divan.workspace = true

[[bench]]
name = "default"
harness = false
